---
- name: Testing andrewrothstein.lua
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'lua -v'
      ansible.builtin.command: lua -v
      changed_when: false
      register: lua_test_output
    - name: Output from 'lua -v'
      ansible.builtin.debug:
        msg: '{{ lua_test_output.stdout }}'
